import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "cabins",
  description: "Generated by create next app",
};

function CabinsPage() {
  return <div>CabinsPage</div>;
}

export default CabinsPage;
