import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "cabin details",
  description: "Generated by create next app",
};
function CabinDetailPage() {
  return <div>CabinDetailPage</div>;
}

export default CabinDetailPage;
