import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "account",
  description: "Generated by create next app",
};
function AccountPage() {
  return <div>AccountPage</div>;
}

export default AccountPage;
